### ISSUE TITLE
thug analysis not run

### ISSUE THREAD

**Issue by athooora** [buffer/thug#113]
i have successfully installed thug, but while i was executing python thug.py -any url(for any url), the result look like: 

![thug problem](https://cloud.githubusercontent.com/assets/10120096/6603377/c6c2cc00-c832-11e4-9aac-b8e2a82ad328.png)

how do i solve this?

thanks

**Comment by buffer** [comment]
Can you provide additional details? Without such details understanding what is on is impossible for me.

**Comment by athooora** [comment]
When I run thug by typing the command:
Python thug.py adskdoom.info/1e5143e/dc364a.exe
The result of this is look like:
![thug](https://cloud.githubusercontent.com/assets/10120096/6655031/5a0b82f2-cafb-11e4-81df-efaed8f506e1.png)

For any URL I use the result is only this three line.
I think that there is some problem, because the tool doesn’t do the analysis for any provided URL.

**Comment by buffer** [comment]
Are you sure all the dependencies are properly installed? Can you please double check it? Otherwise take a look at

https://github.com/buffer/thug/blob/master/doc/source/docker.rst

for an alternative and extremely simple way to run Thug.

**Comment by athooora** [comment]
hello
i use the docker to install thug and every thing run.
but i need to know where the result of analysis is saved because i need to determine the malicious and benign URL and save it in database. 
can you help me.
thanks

**Comment by buffer** [comment]
Please take a look at the logging documentation

http://buffer.github.io/thug/doc/logging.html

If you have any further questions, please feel free to ask.

**Comment by athooora** [comment]
i looking in this documentation and i find that thug collect the malicious behaviors that observed during the analysis.
i need to know where this malicious behavior is saved?
that i want to use it to determine the malicious website.
thanks

**Comment by buffer** [comment]
These details are documented in the page I referred to in my previous response so I encourage to read it entirely. Moreover I think this request should be directed to the Thug mailing list (you are welcome to join) and not in the issues page which is meant to serve totally different purposes.
