### ISSUE TITLE
Flag to disable MongoDB logging completely

### ISSUE THREAD

**Issue by aikinci** [buffer/thug#121]
I am still stuck with mongodb and it generates problems when I try to run many analyses so it would be really really great if I could just turn it off as an option. Or even better if it would be off per default. Do you think we can do anything about this? Or can you give me a hint of where to start for me to create a patch for you?

Regards

**Comment by buffer** [comment]
Just take a look at Logging/logging.conf

[mongodb]
enable:     True
host:       localhost
port:       27017

Angelo
