### ISSUE TITLE
Feature request: MongoDB logging - analysis cleanup

### ISSUE THREAD

**Issue by wojtossfm** [buffer/thug#128]
Working with Thug while having MongoDB logging left me without a clear mechanism for cleaning up the mongodb database/gridfs. I find thug to be missing a straight forward mechanism for post-analysis cleanup of MongoDB that would take a set of analysis ids as parameters. Has anyone else run into this issue? Providing a common solution that would ship with Thug might be a favorable solution. Any thoughts?

**Comment by buffer** [comment]
I am not sure I understood your request. Basically you would like some kind of mechanism for removing specific analyses from the database/gridfs, right? Could you please further detail the request so that I can properly design and add such code?

**Comment by wojtossfm** [comment]
Yes you understood correctly. The idea is to allow easy cleanup of old and benign analysis entries from the database. Would be nice if it would be tailored both for use as a separate script or a python API call. This is required to make sure the database stays at a manageable size.

```
./utils/mongo_analysis_cleanup.py  <analysis_id> [<analysis_id> [...]]
```

Not sure how you would like to implement it in code, but probably extending the MongoDB logging handler would be straightforward as it already has access to all of the collections.
```
src/Logging/modules/MongoDB.py
```

Does this sound like something that you or other users might also find useful in your use-cases?

**Comment by buffer** [comment]
Sincerely speaking I never used to cleanup the analysis database but if you think it could be useful in some situations that means it should be done. Moreover it should be quite straightforward to do. Please ping me in the next days since this is an extra busy period for me so a human reminder is really worth having :) Thanks for your patience.

**Comment by buffer** [comment]
Feature implemented. Thanks for the suggestion!

**Comment by wojtossfm** [comment]
Thank you very much for this feature. I still hope to get on the other proposed option, but am slightly swamped recently and it may be a while before I get to it. Thank you very much for implementing this.
