### ISSUE TITLE
Feature request: setup.py for installation of Thug

### ISSUE THREAD

**Issue by mjmj** [buffer/thug#129]
It would be very nice to have a setup.py to use for installation of everything.

Thanks!

**Comment by buffer** [comment]
Sincerely speaking I was starting thinking adding a Docker to the repository which should really ease the pain of going through the installation of all of the dependencies. Something already exists as you can read here 

http://buffer.github.io/thug/doc/docker.html

but an official Docker is probably worth doing. Thoughts?

**Comment by mjmj** [comment]
That's true, and I have installed that and it worked. But I just found it a bit uncommon to not have a python installation method with a python api and would think that's the standard way to install it so imports are easy when writing applications around thug. So I don't have to do strange things like append system path's just to find the API, import it and use it.

**Comment by buffer** [comment]
A requirements.txt was added for such purpose. This should ease up installation, for example through pip:

pip install -r requirements.txt

Not all modules are available through pypi, but at least many of them do.

**Comment by mjmj** [comment]
That's fantastic. Thank you!


On September 2, 2015 at 7:47:13 AM, buffer (notifications@github.com) wrote:

A requirements.txt was added for such purpose. This should ease up installation, for example through pip:

pip install -r requirements.txt

Not all modules are available through pypi, but at least many of them do.
