### ISSUE TITLE
Duplicate graphviz python libs referenced in requirements.txt

### ISSUE THREAD

**Issue by aikinci** [buffer/thug#139]
in the requirements there two python interfaced for the graphviz library referenced. I figure that one of them is outdated. 

    graphviz==0.4.6
    pygraphviz==1.2
A search for imports reveals the only use in 

    src/Logging/modules/Mapper.py:import pygraphviz
So I guess graphviz==0.4.6 is irrelevant?

**Comment by buffer** [comment]
Sure, graphviz could (and should) be removed. I will take care of it later today or you can open a pull request and I will accept it soon.
