### ISSUE TITLE
V8 and PyV8 Google Code

### ISSUE THREAD

**Issue by kevthehermit** [buffer/thug#143]
This is taken from the Google Code website https://code.google.com/p/support/wiki/ReadOnlyTransition

```
After January 2016 you will no longer be able to access source code from a version control client; however project data will still be available from the Google Code Archive.
```

I know that V8 has officially moved to https://github.com/v8/v8
but i cant find a new pyv8

**Comment by kevthehermit** [comment]
I think this will have a big knock on effect with PyV8 which is full of code.google.com SVN checks for V8, GYP, Cygwin etc

**Comment by buffer** [comment]
PyV8 is on Github (https://github.com/flier/pyv8) and I created a fork as well (https://github.com/buffer/pyv8. From January on, PyV8 setup.py will require some changes as you already pointed out. I hope to get rid of PyV8 soon but I will take care of it in such case.

**Comment by kevthehermit** [comment]
Appreciate all your work

**Comment by JohannesTK** [comment]
Any news? Because right now all new installations of Thug's are broken. 

As in the official doc: https://buffer.github.io/thug/doc/build.html the Google V8/PyV8 part fails because of the svn checkout fails. 

Do you have plans to get it fixed so new users can still use Thug?

**Comment by buffer** [comment]
The workaround is ready and is going to be published in the next hours so please stay tuned!

**Comment by buffer** [comment]
Thug 0.7 released with the V8/PyV8 brand new installation procedure. Take a look at the documentation and you will learn how to install both of them with a single command :)

**Comment by JohannesTK** [comment]
Tested and working. 

Btw, great project and job for making the infosec community a better one!
