### ISSUE TITLE
Compiling error in V8/PyV8 on CentOS 6.7 64bit

### ISSUE THREAD

**Issue by rapedme** [buffer/thug#145]
The follow issue below deals with the patching and compiling of V8/PyV8 when executed on CentOS 6.7 x86_64 bit.

environment
<pre>
cat /etc/redhat-release 
   CentOS release 6.7 (Final)
uname 
  Linux 2.6.32-573.12.1.el6.x86_64 x86_64
</pre>

chechout v8
<pre>
cd /work/wha/deps
svn checkout http://v8.googlecode.com/svn/trunk/ v8
</pre>

patching pyv8
<pre>
svn checkout http://pyv8.googlecode.com/svn/trunk/ pyv8
patch -p0 < PyV8-patch1.diff 
patching file pyv8/src/Context.cpp
Hunk #1 succeeded at 137 with fuzz 2 (offset 4 lines).
</pre>

package install
<pre>
yum install systemtap-sdt-devel  # for dtrace
yum install boost-devel boost-python # for boost
rpm -qa | grep boost
boost-python-1.41.0-27.el6.x86_64
boost-filesystem-1.41.0-27.el6.x86_64
boost-date-time-1.41.0-27.el6.x86_64
boost-graph-1.41.0-27.el6.x86_64
boost-test-1.41.0-27.el6.x86_64
boost-serialization-1.41.0-27.el6.x86_64
boost-1.41.0-27.el6.x86_64
boost-devel-1.41.0-27.el6.x86_64
boost148-python-1.48.0-7.el6.x86_64
boost-system-1.41.0-27.el6.x86_64
boost-thread-1.41.0-27.el6.x86_64
boost-wave-1.41.0-27.el6.x86_64
boost-regex-1.41.0-27.el6.x86_64
boost-program-options-1.41.0-27.el6.x86_64
boost-iostreams-1.41.0-27.el6.x86_64
boost-signals-1.41.0-27.el6.x86_64
boost-math-1.41.0-27.el6.x86_64
</pre>

> export V8_HOME=/work/wha/deps/v8
> python setup.py build

<pre>
INFO: Found Google v8 base on V8_HOME </work/wha/deps/v8/>
running build
INFO: we will try to update v8 to SVN r19632 at <http://v8.googlecode.com/svn/trunk/>
====================
INFO: Checking out or Updating Google V8 code from SVN...

INFO: we will try to use the system 'svn' command to checkout/update V8 code
--------------------
INFO: checkout or update Google V8 code from SVN ...
DEBUG: > svn up /work/wha/deps/v8/ -r 19632
====================
INFO: Installing or updating GYP...
--------------------
INFO: Check out GYP from SVN ...
DEBUG: > make dependencies
====================
INFO: Patching the GYP scripts
INFO: skip to patch the Google v8 build/standalone.gypi file 
====================
INFO: building Google v8 with GYP for x64 platform with release mode
--------------------
INFO: build v8 from SVN ...
DEBUG: > make -j 8 objectprint=off i18nsupport=off verifyheap=off debuggersupport=on regexp=native vtunejit=off extrachecks=off visibility=on snapshot=on strictaliasing=on liveobjectlist=off backtrace=on gdbjit=off disassembler=off werror=no library=shared x64.release
--------------------
INFO: generate DTrace probes.h ...
DEBUG: > dtrace -h -C -s /work/wha/deps/pyv8/src/probes.d -o /work/wha/deps/pyv8/src/probes.h
--------------------
INFO: generate DTrace probes.o ...
DEBUG: > dtrace -G -C -s /work/wha/deps/pyv8/src/probes.d -o /work/wha/deps/pyv8/build/probes.o
running build_py
running build_ext
building '_PyV8' extension
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DBOOST_PYTHON_STATIC_LIB -DV8_NATIVE_REGEXP -DENABLE_DEBUGGER_SUPPORT -DV8_TARGET_ARCH_X64 -I/work/wha/deps/v8/include -I/work/wha/deps/v8/ -I/work/wha/deps/v8/src -I/usr/local/include -I/usr/include/python2.6 -c src/Utils.cpp -o build/temp.linux-x86_64-2.6/src/Utils.o -Wno-write-strings -g -O3
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DBOOST_PYTHON_STATIC_LIB -DV8_NATIVE_REGEXP -DENABLE_DEBUGGER_SUPPORT -DV8_TARGET_ARCH_X64 -I/work/wha/deps/v8/include -I/work/wha/deps/v8/ -I/work/wha/deps/v8/src -I/usr/local/include -I/usr/include/python2.6 -c src/Exception.cpp -o build/temp.linux-x86_64-2.6/src/Exception.o -Wno-write-strings -g -O3
src/Exception.cpp: In member function ‘void CJavascriptException::PrintCallStack(boost::python::api::object)’:
src/Exception.cpp:434: error: ‘class boost::python::api::object’ has no member named ‘is_none’
error: command 'gcc' failed with exit status 1
</pre>

error found 
<pre>
src/Exception.cpp:434: error: ‘class boost::python::api::object’ has no member named ‘is_none’
error: command 'gcc' failed with exit status 1
</pre>

**Comment by buffer** [comment]
Seems like it is due to an old version of boost python being installed on your distro. Just a tip. Be careful with CentOS since this distro does not update its repositories really frequently so you could be forced to update manually. Let me know.

**Comment by rapedme** [comment]
I try .... 
install boost-devel version 1.59
refs : http://vicendominguez.blogspot.kr/2014/04/boost-c-library-rpm-packages-for-centos.html
ok .. clean..

and..error found.

File "/work/wha/project/src/DOM/W3C/HTML/compatibility.py", line 5, in <module>
...
File "/work/wha/project/src/DOM/compatibility.py", line 5, in <module>
...
File "/work/wha/project/src/Logging/modules/compatibility.py", line 5, in <module>
..
    if sys.version_info.major >= 3:
AttributeError: 'tuple' object has no attribute 'major'

fix : Python 2.6. Please use sys.version_info[0] 
-if sys.version_info.major >= 3:
+if sys.version_info[0] >= 3:

Thanks you a lot ~~

**Comment by buffer** [comment]
FYI Python 2.6 is not supported so there could be other related issues. I would suggest you updating to Python 2.7, if possible.
