### ISSUE TITLE
Error in comments about the license?

### ISSUE THREAD

**Issue by RyDroid** [buffer/thug#155]
Hi.

https://github.com/buffer/thug/blob/master/README.md
> License: GNU General Public License, version 2 or later;

But when I opened the source code, I saw that: (for example: https://github.com/buffer/thug/blob/master/src/ThugAPI/ThugAPI.py)
```
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
```

For applying GPL version 2 or later, the FSF (it is in GPL license text) recommends that:
> This program is free software; you can redistribute it and/or modify
> it under the terms of the GNU General Public License as published by
> the Free Software Foundation; either version 2 of the License, or
> (at your option) any later version.

So in the above comment, "or (at your option) any later version" is missing. For me, it is an important difference.
Is it just an error that should be fixed in the comments or an error in README?

Regards.

**Comment by buffer** [comment]
Just an error in README. Thanks for pointing it out!
