### ISSUE TITLE
Error while building docker image from Dockerfile

### ISSUE THREAD

**Issue by standa4** [buffer/thug#187]
Hello, 
I am having an issue with building docker image from your Dockerfile and it also seems that the version on duckerhub (https://hub.docker.com/r/buffer/thug/) has the same problem. 
Last working version was 0.8.6
It looks like there is a problem with Graphviz. I don't know how to solve this issue. Could you look at 
it? Thank you.
Following is the error output:

...
...
  Found existing installation: pygraphviz 1.4rc1
    Uninstalling pygraphviz:
      Successfully uninstalled pygraphviz
  Running setup.py install for pygraphviz
    Trying pkg-config
    Failed to find pkg-config
    Trying dotneato-config
    Failed to find dotneato-config
    Failed to find dotneato-config
    
    Your Graphviz installation could not be found.
    
            1) You don't have Graphviz installed:
               Install Graphviz (http://graphviz.org)
    
            2) Your Graphviz package might incomplete.
               Install the binary development subpackage (e.g. libgraphviz-dev or similar.)
    
            3) You are using Windows
               There are no PyGraphviz binary packages for Windows but you might be
               able to build it from this source.  See
               http://networkx.lanl.gov/pygraphviz/reference/faq.html
    
            If you think your installation is correct you will need to manually
            change the include_dirs and library_dirs variables in setup.py to
            point to the correct locations of your graphviz installation.
    
            The current setting of library_dirs and include_dirs is:
    library_dirs=None
    include_dirs=None
    
    error: Error locating graphviz.
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/pygraphviz/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-gD0jtR-record/install-record.txt --single-version-externally-managed --compile:
    running install

Trying pkg-config

Failed to find pkg-config

Trying dotneato-config

Failed to find dotneato-config

Failed to find dotneato-config

Your Graphviz installation could not be found.

        1) You don't have Graphviz installed:

           Install Graphviz (http://graphviz.org)

        2) Your Graphviz package might incomplete.

           Install the binary development subpackage (e.g. libgraphviz-dev or similar.)

        3) You are using Windows

           There are no PyGraphviz binary packages for Windows but you might be

           able to build it from this source.  See

           http://networkx.lanl.gov/pygraphviz/reference/faq.html

        If you think your installation is correct you will need to manually

        change the include_dirs and library_dirs variables in setup.py to

        point to the correct locations of your graphviz installation.

        The current setting of library_dirs and include_dirs is:

library_dirs=None

include_dirs=None

error: Error locating graphviz.

----------------------------------------
  Rolling back uninstall of pygraphviz
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1440, in install
    requirement.rollback_uninstall()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 604, in rollback_uninstall
    self.uninstalled.rollback()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1864, in rollback
    pth.rollback()
AttributeError: 'str' object has no attribute 'rollback'

Storing debug log for failure in /root/.pip/pip.log
The command '/bin/sh -c pip install thug' returned a non-zero code: 2

**Comment by buffer** [comment]
While investigating the issue with @pdelsante we realized that the issue should be strictly related to the new pygraphviz version (1.4rc1). Hope to provide a workaround as soon as possible. Thanks for your patience!

**Comment by buffer** [comment]
Thanks to @pdelsante the docker image works again!

**Comment by vishu0047** [comment]
Running setup.py clean for pygraphviz
Failed to build pygraphviz
Installing collected packages: simplegeneric, six, scandir, pathlib2, pickleshare, backports.shutil-get-terminal-size, ptyprocess, pexpect, enum34, ipython-genutils, decorator, traitlets, pygments, wcwidth, prompt-toolkit, setuptools, ipython, protobuf, numpy, scipy, configparser, entrypoints, MarkupSafe, jinja2, jupyter-core, functools32, jsonschema, nbformat, testpath, mistune, webencodings, html5lib, bleach, pandocfilters, nbconvert, pyzmq, python-dateutil, futures, singledispatch, backports-abc, tornado, jupyter-client, ipykernel, terminado, Send2Trash, notebook, widgetsnbextension, ipywidgets, qtconsole, jupyter-console, jupyter, pygraphviz, syntaxnet-with-tensorflow
  Running setup.py install for pygraphviz ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-A3wBcy/pygraphviz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-O_Olg8-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    Trying pkg-config
    Failed to find pkg-config
    Trying dotneato-config
    Failed to find dotneato-config
    Failed to find dotneato-config

    Your Graphviz installation could not be found.

            1) You don't have Graphviz installed:
               Install Graphviz (http://graphviz.org)

            2) Your Graphviz package might incomplete.
               Install the binary development subpackage (e.g. libgraphviz-dev or similar.)

            3) You are using Windows
               There are no PyGraphviz binary packages for Windows but you might be
               able to build it from this source.  See
               http://networkx.lanl.gov/pygraphviz/reference/faq.html

            If you think your installation is correct you will need to manually
            change the include_dirs and library_dirs variables in setup.py to
            point to the correct locations of your graphviz installation.

            The current setting of library_dirs and include_dirs is:
    library_dirs=None
    include_dirs=None

    error: Error locating graphviz.

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-A3wBcy/pygraphviz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-O_Olg8-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-A3wBcy/pygraphviz/

please provide the fix

**Comment by buffer** [comment]
Reading the documentation [1] is usually a good way to fix non existent issues. 

[1] https://buffer.github.io/thug/doc/build.html
