### ISSUE TITLE
Thug Api import error 

### ISSUE THREAD

**Issue by rashidali242** [buffer/thug#195]
i am getting an error on command python thug.py -h ,

"Traceback (most recent call last):
  File "thug.py", line 24, in <module>
    from .ThugAPI import ThugAPI
ValueError: Attempted relative import in non-package"

**Comment by buffer** [comment]
This way of executing is no longer supported. Just install it as explained in documentation and execute the "thug" command.

**Comment by rashidali242** [comment]
I installed it as in documentation i solved all the issue now how to test thug to know it is correctly installed or not ?

**Comment by buffer** [comment]
Just run 'thug' :)
