### ISSUE TITLE
Not Issue - Need Help, Its urgent

### ISSUE THREAD

**Issue by rashidali242** [buffer/thug#198]
Hope you are good. 
can you let me know how to detect malicious website using thug. I search for it on google but i did not get any help.  I used the following command 
python thug.py https://www.google.com 
This command generate a log in the logs folder where i can found analysis.xml file but in that file i did not found any such node which can help to conclude that the url is trusted or not ?
My goal is to detect malicious website using thug so i need your help regarding this. 
thanks in advance .

**Comment by buffer** [comment]
I spent a huge amount of time in documenting every single detail of Thug so you should spend some time taking a look at it

http://buffer.github.io/thug/doc/index.html
