### ISSUE TITLE
Please Update your Wiki!

### ISSUE THREAD

**Issue by Philelis** [buffer/thug#204]

**Comment by buffer** [comment]
The official documentation is available at https://buffer.github.io/thug/doc/index.html so there is no reason to have those old pages into the Wiki. For this reason I am going to remove its contents. Thanks for pointing it out and please refer to such link from now on.

**Comment by Philelis** [comment]
Ok thanks for that. It would be nice to see this link on your readme, otherwise it is easy to miss it.

**Comment by buffer** [comment]
Actually it is :) 

> Documentation about Thug installation and usage can be found in the source tree or alternatively at https://buffer.github.com/thug/

Moreover for user convenience the documentation is also available in the tree in the _docs_ directory. If you move to such directory and run _make html_ you will end up having it available locally as well.
