### ISSUE TITLE
Need list of all events 

### ISSUE THREAD

**Issue by seantree** [buffer/thug#215]
Hi 

just want to know the list of events that handled by thug.

like we have click, mouseover, pageload. So I need list of all events that should be enabled and handled correctly by thug.

**Comment by buffer** [comment]
In theory, Thug handles almost all the events as reported at

https://www.w3.org/wiki/List_of_events

if an handler is attached to an element in the page. Most of the times you just need to enable click other than pageload and mouseover (enabled by default).
