### ISSUE TITLE
Whitelisting URLs

### ISSUE THREAD

**Issue by tomdaq** [buffer/thug#220]
Thug is following links and crawling well-known domains, which is something I don't need.  I would like to filter or whitelist a bunch of URLs to prevent such behavior but I can't find any relevant documentation on how to accomplish this.  Can you provide some documentation/examples for how to enable URL filtering?

**Comment by buffer** [comment]
You can do that using the URL filter feature

--urlfilter= Specify a list of additional (comma separated) URL filter files

Please note that you can use this same feature through API as well. Basically all you need to is to create a Yara signature file (https://virustotal.github.io/yara/) using URLs and/or regex's as strings. In case of match, Thug will note the URL in the logs but will avoid crawling it.

**Comment by tomdaq** [comment]
Thanks for the details.  To do it in a Yara rule, I'm not clear about what external variable to reference.  Or do I just need to specify a variable in the "strings" and reference it in a "condition" statement?  So something like the following should work?

rule whitelist
{
    strings:
        $url1 = /https\:\/\/code\.jquery\.com/
        $url2 = /https\:\/\/fonts\.googleapis\.com/

    condition:
        $url1 or $url2
}

**Comment by buffer** [comment]
The rule is correct and will work fine. Just a tip. Using '1 of them' as condition would allow you to add a lot of URLs to check and not to change the condition every time you add a new one.

**Comment by tomdaq** [comment]
Got it.  Thanks a bunch!

**Comment by buffer** [comment]
No problem!
