### ISSUE TITLE
Need a plugin logging method

### ISSUE THREAD

**Issue by tomdaq** [buffer/thug#221]
I am collecting some information in a pre analysis plugin that I would like to include in MongoDB (or whatever logging option is in use).  Extending the schema to include a plugin-id collection would be ideal.

**Comment by buffer** [comment]
Can you please furnish additional details about your requirements so that I can better understand what you really need to log? Thanks!

**Comment by tomdaq** [comment]
Sure.  I'm pulling UrlInfo details from Amazon Web Information Service:  https://docs.aws.amazon.com/AlexaWebInfoService/latest/ApiReference_UrlInfoAction.html

Specifically, the SiteData:
```
<aws:SiteData>
<aws:Title>Yahoo!</aws:Title>
<aws:Description>Personalized content and search options. Chatrooms, free e-mail, clubs, and pager.</aws:Description>
<aws:OnlineSince>18-Jan-1995</aws:OnlineSince>
</aws:SiteData>
```
LinksInCount and OwnedDomains:
```
<aws:LinksInCount>76894</aws:LinksInCount>
<aws:OwnedDomains>
<aws:OwnedDomain>
  <aws:Domain>yahooligans.com</aws:Domain>
  <aws:Title>yahooligans.com</aws:Title>
</aws:OwnedDomain>
</aws:OwnedDomains>
```
and Rank:
```
  <aws:Rank>
    <aws:Value>1</aws:Value>
    <aws:Delta>+0</aws:Delta>
  </aws:Rank>
```
I don't see any need to retain the original XML format so if I need to reformat it to JSON before logging it, that's ok.

Thanks for entertaining the idea!

**Comment by buffer** [comment]
That sounds a really interesting feature! What do you think about embedding it in Thug? We could make it optional and design a proper logging schema extension

**Comment by tomdaq** [comment]
That would be awesome.  A setting to enable it and specify the API key and
secret key somewhere in /etc/thug would be perfect.

**Comment by buffer** [comment]
That's exactly what I was thinking about! Would you mind sending a PR? Otherwise feel free to send a private email so that we can talk about it. Thanks!

**Comment by buffer** [comment]
I am sorry but I totally lost track of this ticket. Are you still interested in the feature? If yes, I could work on it in the next days. Please let me know.

**Comment by buffer** [comment]
Feature implemented. Closing the issue.
