### ISSUE TITLE
Requires.io [Enhancement]

### ISSUE THREAD

**Issue by kira0204** [buffer/thug#225]
Hi,
We can include `requires.io` to monitor the dependencies and update them automatically. 
What do you think about this?

**Comment by buffer** [comment]
Included. Thanks for the suggestion! BTW I don't think that updating the requirements automatically is the best thing to do. I think that just being alerted about some updates and then evaluate if the updating is worth doing is probably the best strategy.

**Comment by kira0204** [comment]
That also sounds great.
