### ISSUE TITLE
Text flowing out of the box for graph.svg

### ISSUE THREAD

**Issue by armudgal** [buffer/thug#246]
Hi,
The text is flowing out of the boxes currently in `graph.svg` generated.
![image](https://user-images.githubusercontent.com/19341613/43372012-f04efea8-93b9-11e8-95a4-b862c63f1c2f.png)

It seems like the issue is in `pygraphviz` and not `thug` itself and hence will wait for the reply, if that takes too much time, we can have a workaround by changing the font size.

https://github.com/pygraphviz/pygraphviz/issues/161

**Comment by kira0204** [comment]
Hi,
Update: The problem is with the SVG renderer and is not actually an `pygraphviz` issue, I faced the issue with Ubuntu 18.04 and Android 8.0.0(Oreo), will keep this issue open and will dig deeper into this
