### ISSUE TITLE
ssdeep is failed when I used “pip install thug”

### ISSUE THREAD

**Issue by abay123** [buffer/thug#263]
I tried “pip install --upgrade setuptools” then setuptools is upgraded but this problem also exists.

![default](https://user-images.githubusercontent.com/42140379/46799486-81fe3600-cd87-11e8-8dc0-3e62097bd1f8.png)

**Comment by buffer** [comment]
I experienced a similar issue with the latest ssdeep version (3.3) and that's exactly the reason why I was keeping on using version 3.2. Apparently ssdeep build is broken and I was just lucky enough to never experience that. Consider it is an optional library which is used just to evaluate another hash in case a sample is downloaded. For this reason I think the safest option is probably to remove it from requirements. If a user needs it a manual install would be required. But let me do some additional tests before. Thanks for reporting.

**Comment by abay123** [comment]
> 
> 
> I experienced a similar issue with the latest ssdeep version (3.3) and that's exactly the reason why I was keeping on using version 3.2. Apparently ssdeep build is broken and I was just lucky enough to never experience that. Consider it is an optional library which is used just to evaluate another hash in case a sample is downloaded. For this reason I think the safest option is probably to remove it from requirements. If a user needs it a manual install would be required. But let me do some additional tests before. Thanks for reporting.

Thank you very much for your reply. I'm flattered. But I still report the same error when I use PIP install ssdeep==3.2. Using PIP install thug to download the python wrapped third-party module thug, ssdeep is a must. Please let me know after your test. Thank you very much.

**Comment by abay123** [comment]
> 
> 
> I experienced a similar issue with the latest ssdeep version (3.3) and that's exactly the reason why I was keeping on using version 3.2. Apparently ssdeep build is broken and I was just lucky enough to never experience that. Consider it is an optional library which is used just to evaluate another hash in case a sample is downloaded. For this reason I think the safest option is probably to remove it from requirements. If a user needs it a manual install would be required. But let me do some additional tests before. Thanks for reporting.


Could you please give me your twitter or facebook account

**Comment by armudgal** [comment]
Hi @abay123, this looks like a `ssdeep` issue, can you raise the issue on their repo as well. Will take a look into this in couple of hours, thanks.

**Comment by abay123** [comment]
I thought this was a problem with the ssdeep module or the python version originally in kali, so I switched to the version of ubuntu16 to try it out, and the same error was reported again when I installed pylibemu. Now I think it's due to python2.7.3

**Comment by abay123** [comment]
> 
> 
> Hi @abay123, this looks like a `ssdeep` issue, can you raise the issue on their repo as well. Will take a look into this in couple of hours, thanks.

OK thank you for your suggestion.

**Comment by rjsnh1522** [comment]
I am trying to install thug but still getting same error.
any update on this ?. How to install and run it ?

**Comment by buffer** [comment]
This is a ssdeep "issue" and it seems like there's not just one recipe to solve that. Please take a look at https://python-ssdeep.readthedocs.io/en/latest/installation.html. It seems like different distros/versions require different steps. Once ssdeep is manually installed, Thug installation should work fine. I prefer not changing the way Thug is currently installed now because it will probably fix a platform and break some others.

**Comment by rjsnh1522** [comment]
Now ssdeep issue is gone. but pyv8 is not able to link something.

`_LIB -DV8_NATIVE_REGEXP -DENABLE_DEBUGGER_SUPPORT -DV8_TARGET_ARCH_X64 -I/Users/logan/workspace/office/thug/pyv8/build/v8_r19632/include -I/Users/logan/workspace/office/thug/pyv8/build/v8_r19632 -I/Users/logan/workspace/office/thug/pyv8/build/v8_r19632/src -I/opt/local/include -I/usr/local/include -I/Users/logan/miniconda3/envs/thug_life/include/python2.7 -c src/PyV8.cpp -o build/temp.macosx-10.6-x86_64-2.7/src/PyV8.o -g -O3 -Wdeprecated-writable-strings -Wno-tautological-undefined-compare -Wno-deprecated-declarations -stdlib=libc++
g++ -bundle -undefined dynamic_lookup -L/Users/logan/miniconda3/envs/thug_life/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.6-x86_64-2.7/src/Utils.o build/temp.macosx-10.6-x86_64-2.7/src/Exception.o build/temp.macosx-10.6-x86_64-2.7/src/Context.o build/temp.macosx-10.6-x86_64-2.7/src/Engine.o build/temp.macosx-10.6-x86_64-2.7/src/Wrapper.o build/temp.macosx-10.6-x86_64-2.7/src/Debug.o build/temp.macosx-10.6-x86_64-2.7/src/Locker.o build/temp.macosx-10.6-x86_64-2.7/src/AST.o build/temp.macosx-10.6-x86_64-2.7/src/PrettyPrinter.o build/temp.macosx-10.6-x86_64-2.7/src/PyV8.o -L/usr/local/lib -L/Users/logan/workspace/office/thug/pyv8/build/v8_r19632/out/x64.release/ -L/Users/logan/miniconda3/envs/thug_life/lib -lboost_python-mt -lboost_thread-mt -lboost_system-mt -lv8_base.x64 -lv8_snapshot -o build/lib.macosx-10.6-x86_64-2.7/_PyV8.so -fPIC
ld: warning: directory not found for option '-L/Users/logan/workspace/office/thug/pyv8/build/v8_r19632/out/x64.release/'
ld: library not found for -lboost_python-mt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'g++' failed with exit status 1`

I think linker is not able to link something

**Comment by buffer** [comment]
Technically speaking Mac OS X is not supported but I use Thug on Mojave as well so I know how to fix that. If you installed boost using brew, just uninstall it, download Boost from this link

https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.gz

and install it from source. That's quite easy to do cause it's a single command IIRC. I think the issue is about the brew boost package. This workaround works great here. Please let me know.

**Comment by rjsnh1522** [comment]
Now it's working finally thanks.
For future reference:
I installed thug from pip `pip install thug`
downloaded pyv8 from [https://github.com/emmetio/pyv8-binaries](url)

and copied the extracted **_PyV8.so** and **PyV8.py** file inside `myvenv/lib/python2.7`

and everything is worked.

**Comment by buffer** [comment]
That's a very interesting alternative way of setting it up. Thanks for pointing it out!

**Comment by buffer** [comment]
FYI upgraded ssdeep to version 3.4. This seems to fix the issue here. I am going to perform some tests and release a new version in the next days in case of no issues.
