### ISSUE TITLE
Clean up Travis config file

### ISSUE THREAD

**Issue by armudgal** [buffer/thug#264]
Hey,
Right now we are directly mentioning all the steps that need to be done for `Thug configuration` in the config file for Travis (https://github.com/buffer/thug/blob/cff4114a8008caf1791083245f38b4cfbdeac9d0/.travis.yml#L12-L20). 
It would be better if we move all these steps to a seperate file and then execute the file from travis.

**Comment by armudgal** [comment]
Hi, I was wondering if this issue remains open, it can act as a beginner-friendly issue.

**Comment by Montana** [comment]
Hi @armudgal, 

Why don't you just make a bash script?

```bash
#!/bin/bash

set -e

sudo apt-get update
sudo apt-get install libboost-python-dev libboost-all-dev systemtap-sdt-dev libfuzzy-dev graphviz

sudo pip install pylibemu
pip install tox

echo "/opt/libemu/lib/" | sudo tee --append /etc/ld.so.conf.d/libemu.conf && sudo ldconfig

sudo mkdir -p /etc/thug/rules /etc/thug/personalities /etc/thug/scripts

sudo cp -R thug/Classifier/rules/* /etc/thug/rules/
sudo cp -R thug/DOM/personalities/* /etc/thug/personalities/
sudo cp -t /etc/thug/scripts thug/DOM/{thug.js,storage.js,date.js} thug/Debugger/d8.js
sudo cp -t /etc/thug/ thug/Analysis/honeyagent/honeyagent.conf.sample thug/Analysis/virustotal/virustotal.conf.default thug/Logging/logging.conf.default

tox

echo "Build done"
```

I even made it for you.
