### ISSUE TITLE
Error while installing 

### ISSUE THREAD

**Issue by mzfr** [buffer/thug#269]
I am trying to setup a development environment so after cloning the repo when I try to run `./dev/dev.sh` I am getting [this](https://drive.google.com/file/d/1nBbWdMwzWSTaqcB2666yJET__nX84y2D/view?usp=sharing) error.

I am using Manjaro OS with python 2.7.

**Comment by armudgal** [comment]
Hi, I will get back to this as soon as possible.

**Comment by armudgal** [comment]
Hello, is this resolved?

**Comment by mzfr** [comment]
Hey, @armudgal This issue is not fixed. Even though I was able to run thug in VM but this is still unclear why this happens?

**Comment by armudgal** [comment]
It seems that there is a problem with the gcc in Manjaro, what is the version of gcc on your machine?

**Comment by mzfr** [comment]
@armudgal `gcc version 8.2.1 20181127 (GCC)`

**Comment by rjsnh1522** [comment]
I am trying to install thug but still getting same error.
any update on this ?. How to install and run it ?

**Comment by buffer** [comment]
Closing this issue before the next major release of Thug (which is going to happen in the next days). The development environment is clearly broken and I am going to drop it as the new stuff I am going to introduce will reasonably make things worse.
