### ISSUE TITLE
Use argparse instead of getopt

### ISSUE THREAD

**Issue by mzfr** [buffer/thug#270]
Currently, thug use `getopt` for argument parsing but since `argparse` is considered better and is also [suggested](https://pymotw.com/3/getopt/#Note) over `getopt` I think we should switch to argparse. 

For more read: https://www.python.org/dev/peps/pep-0389/#why-aren-t-getopt-and-optparse-enough

**Comment by buffer** [comment]
Well, sincerely speaking, I think getopt does exactly what's needed for the command-line tool. Moreover it's currently maintained and not even deprecated. Replacing code that works fine just because someone says it's better does not make great sense to me.
