### ISSUE TITLE
Timeout option not working properly

### ISSUE THREAD

**Issue by PinkSheep** [buffer/thug#273]
Hello
Is it possible that the timeout option (-T) is not working as intended? I was scanning some targets that take a long time or never finish at all (longer than the 600s default timeout), where I noticed that the runs actually don't finish after the default timeout. I still see the timeout message in the log: `[2019-03-19 09:09:30] The analysis took more than 60 second(s). Aborting!` however the run is not stopped as result, rather it continues as if nothing happened. The same behaviour was occurring after choosing different targets and a shorter timeout.

I am running thug inside a docker container and am starting the scans with the following command (short timeout for testing purposes): `docker run --rm -it buffer/thug thug -T 10 -d <target url>`

I am misinterpreting what the timeout option is for? I am assuming it should abort the scan as soon as the timeout is reached, but maybe that is not the case.

**Comment by buffer** [comment]
It should not happen. I use that option very frequently and never experienced such issue in a non-docker environment. Which version of Thug are you using? Moreover can you please share some URLs (if possible) so that I can try to reproduce the misbehavior? Thanks!

**Comment by PinkSheep** [comment]
Hm, I have not tested it yet in a non docker environment. Maybe that's the issue. I have used version 0.9.39 from your docker image on Dockerhub and version 0.9.44 from a docker image I've build myself, same behaviour in both version.

As for URLs I was testing some google drive URLs that contained links to malware, which I wont share here for obvious reasons :-) Alternatively you can test the same behaviour on my universities site ([www.zhaw.ch](www.zhaw.ch)) where I get the same result and which should be ok to test.

In the meantime I'll try to perform the same scan in a non docker environment.

**Comment by PinkSheep** [comment]
Ok it is definitely the docker environment that is causing the issue. I've executed the same scan in a non docker environment and the scan aborts as intended after the timeout period.

**Comment by buffer** [comment]
That's (partially) good news. Thanks for providing such useful information. Will keep this issue open and try to take a look at it soon.

**Comment by PinkSheep** [comment]
I did some further digging and found the root cause: Apparently docker ignores SIGTERM requests to pid 1 (which thug runs as in a docker container). See [this article](https://hackernoon.com/my-process-became-pid-1-and-now-signals-behave-strangely-b05c52cc551c) for reference.

If you want to fix the issue you should probably replace the `os.kill(os.getpid(), signal.SIGTERM)` kill command in the [Watchdog](https://github.com/buffer/thug/blob/master/thug/ThugAPI/Watchdog.py) class. I tried it with a simple `sys.exit(0)` and this seems to work just fine. My python skills are limited though so maybe this is not the correct approach. If that seems like a good fix i can open a pull request or you can just fix the line yourself :-)

**Comment by buffer** [comment]
Thanks for the great analysis! I committed a patch based on your analysis which performs the same termination routine if PID is not 1 and makes use of sys.exit if the PID is 1. Could you please give it a try?

**Comment by PinkSheep** [comment]
Just tested your fix and the timeout option now works as intended in a docker container :+1:

**Comment by buffer** [comment]
Great news! Thanks again for spotting and investigating it!
