### ISSUE TITLE
ImportError: libemu.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kafin** [buffer/thug#28]
I have successfully installed V8 and PyV8. i have tested it and the result is OK.

but while i was executing python thug.py -h,, the error was appeared. the errors look like: 

root@ubuntu:/home/kafin/thug/src# sudo python thug.py -h
Traceback (most recent call last):
  File "thug.py", line 31, in <module>
    from DOM import Window, DFT, MIMEHandler, SchemeHandler
  File "/home/kafin/thug/src/DOM/Window.py", line 32, in <module>
    from .Location import Location
  File "/home/kafin/thug/src/DOM/Location.py", line 22, in <module>
    import DFT
  File "/home/kafin/thug/src/DOM/DFT.py", line 20, in <module>
    import pylibemu
ImportError: libemu.so.2: cannot open shared object file: No such file or directory

anyone got also this error, or how do i solve this?

thanks

**Comment by twosandals** [comment]
following the setup instructions, i was able to install everything but the last "libemu" using this comand
sudo apt-get install libemu..... any help how to go about this?
thanks

**Comment by kongo86** [comment]
What error message are you getting?

**Comment by twosandals** [comment]
when i run the command: sudo apt-get install libemu,

this is what i get:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libemu

i am running on ubuntu 12.04

**Comment by twosandals** [comment]
going on with the installation and running thug, i get the following error:

aruwa@uglyfish-2:~$ sudo python /opt/thug/src/thug.py -h
Traceback (most recent call last):
  File "/opt/thug/src/thug.py", line 24, in <module>
    from ThugAPI import *
  File "/opt/thug/src/ThugAPI/__init__.py", line 1, in <module>
    from .ThugAPI import ThugAPI
  File "/opt/thug/src/ThugAPI/ThugAPI.py", line 30, in <module>
    from DOM import Window
  File "/opt/thug/src/DOM/Window.py", line 33, in <module>
    import jsbeautifier
ImportError: No module named jsbeautifier

**Comment by buffer** [comment]
1. Libemu is not packaged for Ubuntu so simply following the installation instructions as described in the Thug documentation will solve your issue.
2. You missed installing the jsbeautifier library (again look at the Thug documentation for details).

**Comment by twosandals** [comment]
thanks! but after installing the jsbeautifier library i got so many other error which i was able to fix by installing the individual libraries.
some of which are:
1. magic 
2. requesocks
3. rarfile 
4. lxml

but now it is stuck on reporting this error:
"ImportError: No module named resources"
i am sure all these are supposed to be part of a package which i did not install. i have gone over the thug installation instructions over and over again but cant find where this is.

**Comment by buffer** [comment]
The ImportError refers to internal code and not to external  dependencies. I would suggest you to clone the Thug source again and try again since I fear you messed up the tree. Otherwise give a try to the Thug docker (everything in the docs) which is the simplest way to run Thug.

**Comment by twosandals** [comment]
looking at the errror closely i noticed it was pointing to a dependency in the "Resources" folder which is not available even in the THUG repo. so i had to manually download it from the androguard repository and add it to the local content of thug on my machine and it WORKED!!
so unless there is a mapping in the code to another location which it should pull from, then i guess it wouldnt work even after cloning it again. so maybe you should take a look at this and see
Thanks for your help!!!!
