### ISSUE TITLE
take a screenshot for the page analyzed [feature request]

### ISSUE THREAD

**Issue by yu-yang** [buffer/thug#283]
When analyzing the phishing URL, it would be very convenient to grab a screenshot for the website

**Comment by buffer** [comment]
This is not possible at moment without introducing new dependencies and some additional logic which could reasonably affect performances. Let me think about it but I think it's not something I am going to implement soon.

**Comment by buffer** [comment]
FYI I am testing the feature at the moment. If you want to perform some tests be aware you need to install imgkit which is not installed by default. Please read the installation instructions at [1]. Hopefully there will be another release soon including this feature.

[1] https://pypi.org/project/imgkit/
