### ISSUE TITLE
Static/Dynamic analysis of Form URLs

### ISSUE THREAD

**Issue by morro91** [buffer/thug#302]
Maybe a feature request, maybe a noob question.

I have a sample HTML page with some dynamic javascript that basically constructs a phishing form, it would be kind of cool if this tool could extract the code that occurs when the form is submitted. May not be easy, its in the section of $('#submit-btn').click(...)

Essentially trying to extract the URL it sends the credentials too, even just a strings/regex analysis of all URLs in the final DOM?

Also for more simple forms where the URL is in the <form> tag.

**Comment by buffer** [comment]
Quick question. Have you already tried emulating the click event (the additional option is "-e click")? Please let me know if that provides the information you need. Otherwise I would reasonably need to take a look at the sample.

**Comment by morro91** [comment]
oh nice, didn't see that option. Thanks :)
