### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [buffer/thug#319]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine thug/Logging/ThugLogging.py, thug/Logging/modules/JSON.py, thug/Logging/modules/MongoDB.py and observe `occured`, however expect to see `occurred`.
- Examine README.rst and observe `mimicing`, however expect to see `mimicking`.
- Examine thug/DOM/W3C/HTML/HTMLDocumentCompatibleInfo.py and observe `compatibity`, however expect to see `compatibility`.
- Examine thug/ThugAPI/IThugAPI.py and observe `additionaly`, however expect to see `additionally`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/thug/pull/new/bugfix_typos

Thanks.

**Comment by buffer** [comment]
Please feel free to open a PR and I will take care of merging it. Thanks.

**Comment by timgates42** [comment]
thanks @buffer added PR #320
