### ISSUE TITLE
Block parsing because Google Safe Browsing

### ISSUE THREAD

**Issue by p3ngdump** [buffer/thug#333]
Hello Thug!

I'm trying to detect malicious websites using Thug.
However, when accessing a website registered in Google Safe Browsing, it seems that the original content of the website cannot be parsed.
Is there a way to turn off Google Safe Browsing when Thug parses a website?

thank you!

**Comment by buffer** [comment]
Thug does not make use of Google Safe Browsing at all so I have no idea of what is going on. I suspect you may be using Google DNS servers but I could be wrong

> Does Google Public DNS offer the ability to block or filter out unwanted sites?
Google Public DNS is purely a DNS resolution and caching server; it does not perform any blocking or filtering of any kind, except that it may not resolve certain domains in extraordinary cases if we believe this is necessary to protect Google’s users from security threats.

**Comment by p3ngdump** [comment]
If Thug does not make use of Google Safe Browsing, As you said, it's probably due to Google DNS.

I will check Google DNS.

Thanks buffer!
