### ISSUE TITLE
Dead link for STPyV8 installation

### ISSUE THREAD

**Issue by cccs-kevin** [buffer/thug#367]
Hi @buffer!

It looks like the resource in the Dockerfile for STPyV8 no longer exists. Which release do you recommend instead? https://github.com/cloudflare/stpyv8/releases/tag/v12.0.267.14

Link in Dockerfile: https://github.com/buffer/thug/blob/5d7a3f82f34d6a9ff9352f6deaa8bd4c3dea4dd8/docker/Dockerfile#L71

**Comment by buffer** [comment]
You're totally right. I am going remove that line very soon as STPyV8 is now released to PyPI [1] and can be installed via pip. Thug already takes care of it (take a look at pyproject.toml for details) so no further action is required on the user side.

[1] https://pypi.org/project/stpyv8/
