### ISSUE TITLE
setup.py missing in repo

### ISSUE THREAD

**Issue by klikevil** [buffer/thug#378]
@buffer 
> Are you following the procedure detailed at https://buffer.github.io/thug/doc/build.html#thug-installation ?

Uhhh yeah, https://buffer.github.io/thug/doc/build.html#thug-installation tells you to clone the repo, `python setup.py build` then `sudo python setup.py install`
![image](https://github.com/buffer/thug/assets/32278206/44c42800-6cff-42b3-8413-8dccc629ebe0)

There is no setup.py in the repo for thug, could you please add that I'd like to try the latest because i'm running into issues when it is dealing with event listeners for some odd reason, just built libv8 and stpyv8 then went to build thug and noticed setup.py was missing.  I'm trying to build it under python3.11

_Originally posted by @klikevil in https://github.com/buffer/thug/issues/170#issuecomment-2036039370_

**Comment by buffer** [comment]
The documentation was not correctly updated. The correct command to run locally is

`pip install .`

**Comment by klikevil** [comment]
Thanks so much, that worked perfectly!!!!!
